
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MINUS = 4;
  public static final int ATTRIB = 7;
  public static final int NUMBER = 8;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int ID = 9;
  public static final int error = 1;
  public static final int RPAREN = 6;
  public static final int LPAREN = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "LPAREN",
  "RPAREN",
  "ATTRIB",
  "NUMBER",
  "ID"
  };
}

